### ISSUE TITLE
Bundler failed to load command

### ISSUE THREAD

**Issue by datapolitical** [jeffreytse/jekyll-deploy-action#13]
bundler: failed to load command: jekyll (/github/workspace/vendor/bundle/ruby/2.7.0/bin/jekyll)
139
/github/workspace/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.0/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'vips.so.42': vips.so.42: cannot open shared object file: No such file or directory. (LoadError)
140
Could not open library 'libvips.so.42': libvips.so.42: cannot open shared object file: No such file or directory

**Comment by jeffreytse** [comment]
Hi @datapolitical 

This issue has been addressed and fixed. Please use `jeffreytse/jekyll-deploy-action@master` and try again.

Thanks and regards

**Comment by datapolitical** [comment]
Thanks. I noticed that for some reason your action takes nearly 3 minutes longer to run than my old fork, and they both run fine. Any idea what the slowdown is: ![image](https://user-images.githubusercontent.com/696957/112575556-c3df9300-8dad-11eb-95b4-20f6ca8cac8e.png)

![image](https://user-images.githubusercontent.com/696957/112575563-c8a44700-8dad-11eb-937d-bc8b2b21873b.png)

**Comment by jeffreytse** [comment]
Hi @datapolitical 

Because you run my action after yours, my action will treat as a different OS, this will discard the gems cache and re-install all gems.

Thanks and regards

**Comment by datapolitical** [comment]
I ran yours, then mine, then yours again now. Both times it was slower.

**Comment by jeffreytse** [comment]
@datapolitical Could you provide me the task link that you ran just now?

**Comment by datapolitical** [comment]
https://github.com/datapolitical/chrisfnicholson.github.io/runs/2199067923?check_suite_focus=true

**Comment by jeffreytse** [comment]
@datapolitical, because of the cache is always cleaned up, please see the issue #14 and use the cache key pattern in the code snippet.

**Comment by jeffreytse** [comment]
Hi @datapolitical 

Is this issue settled down? Hope you have a good day! : )

Thanks and regards

**Comment by datapolitical** [comment]
I would just like you to issue a new release.

**Comment by jeffreytse** [comment]
Hi @datapolitical 

Thanks for your patience, I have publish the new reelase [v0.2.1](https://github.com/jeffreytse/jekyll-deploy-action/releases/tag/v0.2.1), now you can update your configuration to it.

Thanks and regards
