### ISSUE TITLE
Q: Do I need to `bundle install` locally anymore?

### ISSUE THREAD

**Issue by Anthonyive** [jeffreytse/jekyll-deploy-action#17]
Hello, I am new to this. Everything is working now. I had some issues where it fails to build, so I did some research and it turns out that I need to delete `Gemfile.lock` in the `main` branch. The error message was this:
```bash
There was an error while trying to write to `/srv/jekyll/Gemfile.lock`. It is
likely that you need to grant write permissions for that path.
Error: Process completed with exit code 23.
```
**I don't have any issue, but just to ask a question.**
I'm wondering if I need to do `bundle install` locally anymore because it builds for me every time. Thank you.

**Comment by jeffreytse** [comment]
Hi @Anthonyive 

I just digged your action record, is this [one](https://github.com/Anthonyive/website/runs/2328659884?check_suite_focus=true)? The error was introduced by the `jekyll/builder` action.

Thanks and regards

**Comment by Anthonyive** [comment]
@jeffreytse Thanks. I have solved the build issue. People suggested to just not include `Gemfile.lock` and it worked perfectly. I'm just wondering if do I need to `bundle install` locally anymore since you know, the workflow essentially build for me on the cloud.

**Comment by jeffreytse** [comment]
@Anthonyive Sure, you can run `bundle install` anytime but just need to add `Gemfile.lock` to your `.gitignore` file to avoid tracking this file, the `Gemfile.lock` content should be as below:

```
_site
.bundle
.sass-cache
.jekyll-metadata
Gemfile.lock
```

**Comment by Anthonyive** [comment]
Got you. Thank you.
