### ISSUE TITLE
Please set the TOKEN environment variable.

### ISSUE THREAD

**Issue by yuceltoluyag** [jeffreytse/jekyll-deploy-action#19]
I changed the name of GH_TOKEN to TOKEN and tried again, I got an error, I deleted and recreated the tokens, I got the same error, I wonder what am I doing wrong?

https://github.com/yuceltoluyag/yuceltoluyag.github.io/runs/2493501445

I created the keys like this

![pic-selected-210503-1856-12](https://user-images.githubusercontent.com/16064131/116900682-b1286b80-ac41-11eb-8f2b-915491e7d438.png)
![pic-selected-210503-1856-37](https://user-images.githubusercontent.com/16064131/116900689-b2599880-ac41-11eb-93b1-0f25ac753f83.png)

**Comment by jeffreytse** [comment]
Hi @yuceltoluyag 

You should create a **Secret** in the secrets tab, but the screentshots show that you are in the **Environment** tab.

![image](https://user-images.githubusercontent.com/9413601/116901885-0b8af180-ac6d-11eb-8fdb-675951c19bbc.png)

Thanks and regards

**Comment by yuceltoluyag** [comment]
@jeffreytse  ![pic-selected-210503-1945-54](https://user-images.githubusercontent.com/16064131/116905964-58a89c80-ac48-11eb-9a5d-6bfc5166bae3.png)
I took the wrong screenshot, I also have a key I created

**Comment by jeffreytse** [comment]
Hi @yuceltoluyag 

You're getting that error because you haven't added your local plugins to your Gemfile. Simply add it to the Gemfile and this error should go away.

```rb
# Gemfile

gem 'jekyll-debug.rb'
gem 'jekyll-groupby.rb'
```

Thanks and regards

**Comment by yuceltoluyag** [comment]
> Hi @yuceltoluyag
> 
> Your plugin should follow the example `_plugins/testplugin.rb`
> 
> ```ruby
> module Jekyll
>   class TestPlugin < Liquid::Tag
>     def render(context)
>       "hello jekyll!"
>     end
>   end
> end
> 
> Liquid::Template.register_tag('testplugin', Jekyll::TestPlugin)
> ```
> 
> Thanks and regards

I don't know ruby language, I thought it would be easy when you said it would work like in the local.

**Comment by jeffreytse** [comment]
Your filter needs to inherit `Liquid::Tag`.

**Comment by yuceltoluyag** [comment]
> Your filter needs to inherit `Liquid::Tag`.

It may be easy for you, not for me but thank you for your answers,
