### ISSUE TITLE
Clarification on 'repos

### ISSUE THREAD

**Issue by jodygarnett** [jeffreytse/jekyll-deploy-action#21]
Your setup instructions asks:

> * Create a Personal Token with repos permissions and copy the value.

What specifically is needed?

* [ ] repo
  * [ ] repo:status
  * [ ] repo_deployment
  * [ ] public_repo
  * [ ] repo:invite
  * [ ] security_events

**Comment by jeffreytse** [comment]
Hi @jodygarnett 

You can assign it with the `repo` permission.

Thanks and regards

**Comment by jodygarnett** [comment]
I was just asking as `repo` provides access to private repositories and so on.

A smaller set of permissions `repo/public_repo` (and possibily `repo/repo_deployment`) may be sufficient for public repositories?

**Comment by jeffreytse** [comment]
Hi @jodygarnett 

Here is the smaller set of permissions:

* [ ] repo
  * [x] repo:status
  * [x] repo_deployment
  * [x] public_repo
  * [ ] repo:invite
  * [ ] security_events

Thanks and regards

**Comment by metapodcod** [comment]
![image](https://user-images.githubusercontent.com/67564813/147016064-35248a46-8dc8-4e61-9776-3ea58a0930f7.png)
@jeffreytse
