### ISSUE TITLE
"error processing package elpa-magit" "emacs: not found"

### ISSUE THREAD

**Issue by MaxGhenis** [jeffreytse/jekyll-deploy-action#25]
See [this run](https://github.com/UBICenter/ubicenter.org/runs/3356228946?check_suite_focus=true#step:2:4023). https://github.com/UBICenter/ubicenter.org/pull/288 caused the break; https://github.com/UBICenter/ubicenter.org/pull/287 was 7 days ago and built fine. I also tried updating to `0.2.1` in https://github.com/UBICenter/ubicenter.org/pull/289, but got the same error.
```
Install git for emacs
  install/git: Handling install of emacsen flavor emacs
  install/git: Byte-compiling for emacs
  + emacs -batch -q -no-site-file -f batch-byte-compile git.el git-blame.el
  /usr/lib/emacsen-common/packages/install/git: 26: emacs: not found
  /usr/lib/emacsen-common/packages/install/git emacs failed at /usr/lib/emacsen-common/lib.pl line 19, <TSORT> line 7.
  dpkg: error processing package elpa-magit (--configure):
   installed elpa-magit package post-installation script subprocess returned error exit status 2
```
Looks like [this](https://www.mail-archive.com/debian-emacsen@lists.debian.org/msg07092.html) might be relevant. Here's our [workflow file](https://github.com/UBICenter/ubicenter.org/blob/master/.github/workflows/deploy.yml).

**Comment by Albert-Z-Guo** [comment]
I got build error related to `elpa-magit` today as well. The build was working fine yesterday.
```
Errors were encountered while processing:
   elpa-magit
  E: Sub-process /usr/bin/dpkg returned an error code (1)
  The command '/bin/sh -c apt-get install -qq -y git-all' returned a non-zero code: 100
```

**Comment by jeffreytse** [comment]
Hi,

Thanks for the reporting, I will try to settle it as soon as possible.

Thanks and Regards

**Comment by jeffreytse** [comment]
Hi @MaxGhenis @Albert-Z-Guo ,

This issue has been settled down, please use version `jekyll-deplay-action@master` and try again.

Thanks and Regards

**Comment by MaxGhenis** [comment]
That worked, thanks @jeffreytse!

**Comment by jeffreytse** [comment]
@MaxGhenis , You're welcome, hope you have a good day! : )

**Comment by Albert-Z-Guo** [comment]
Worked for me as well! Thanks for the quick fix @jeffreytse!

**Comment by jeffreytse** [comment]
@Albert-Z-Guo , You're welcome, hope you have a good day! : )
