### ISSUE TITLE
Website wont build...

### ISSUE THREAD

**Issue by gruvw** [jeffreytse/jekyll-deploy-action#26]
![image](https://user-images.githubusercontent.com/63407038/130149785-239b8148-1c0b-439c-a373-31083ec425fb.png)

Any ideas ?

Everything was building smoothly since now...

**Comment by RiverOnVenus** [comment]
You may need to modify the version of Action. [https://github.com/gruvw/portfolio/blob/6f1a6e8d0f0362af4001e899145dbc82cf751190/.github/workflows/build-jekyll.yml#L23](https://github.com/gruvw/portfolio/blob/6f1a6e8d0f0362af4001e899145dbc82cf751190/.github/workflows/build-jekyll.yml#L23)

**Comment by RiverOnVenus** [comment]
`- uses: jeffreytse/jekyll-deploy-action@master`

**Comment by jeffreytse** [comment]
Hi @gruvw 

This issue has been fixed, you can find more  in issue #25.

Thanks and Regards

**Comment by jeffreytse** [comment]
@RiverOnVenus 👍 Thanks for your quickly help, and hope you have a good day! :)
