### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by MikulasVanousek** [jeffreytse/jekyll-deploy-action#27]
It is not safe to push your personal token to a public repo, right? I know this might seem very obvious to you, but some people might not realize this.

**Comment by jeffreytse** [comment]
Hi @MikulasVanousek 

Thanks for your reaching out. Could you point me out of the place in source code that is not safe? : )

Thanks and Regards

**Comment by MikulasVanousek** [comment]
Sorry, it is not the source code, it is the instructions. You need to generate a personal token and put it into your deploy action. If you push this action to a public GitHub repo, this would expose your personal token to public, right?

**Comment by jeffreytse** [comment]
Hi, I think you misunderstand the [GitHub secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets), it's encrypted and safe for users, and it will not expose others people's personal token to public.

**Comment by MikulasVanousek** [comment]
You are right, probably right. I hope I did not bother you too much. Thank you for your contributions to the open source community.

**Comment by MikulasVanousek** [comment]
When I read the instructions right, it works like a charm. Now I finally can include my ruby script for not requiring date in post filenames.

Once again, thank you for your work and this great repo. Unfortunately, a star is all the support I can give you now, but do not think your work is not being appreciated.

**Comment by jeffreytse** [comment]
@MikulasVanousek Thanks! Hope you have a good day! : )

**Comment by jeffreytse** [comment]
Hi @MikulasVanousek 

Now the latest version has supported to use the `GITHUB_TOKEN` to authenticate in a workflow run, it has better security. You can use the `GITHUB_TOKEN` by using the standard syntax for referencing secrets: `${{ secrets.GITHUB_TOKEN }}`. For more information, you can see the [README](https://github.com/jeffreytse/jekyll-deploy-action/blob/master/README.md).

Thanks and Regards
