### ISSUE TITLE
Action does not fail on authentication issue

### ISSUE THREAD

**Issue by Mexassi** [jeffreytse/jekyll-deploy-action#32]
I am facing an issue where when the authentication fails with:
`remote: Invalid username or password.`

The Action jekyll-deploy-action still passes and my pipeline is green.

I am running version @v0.3.1

**Comment by Mexassi** [comment]
to add more context, I am rotating my tokens. So the GH_TOKEN I was using expired and I have started getting the invalid username or password error.

Updating the secret value fixed the authentication issue, however I would expect the job to fail on authentication errors rather than pass.

**Comment by jeffreytse** [comment]
Hi @Mexassi 

For the version `v0.3.1`,  just use this `${{ secrets.GITHUB_TOKEN }}`, and you don't need to generate the token, Github will auto generate it by default.

Thanks & Regards

**Comment by Mexassi** [comment]
I was not aware of that, thank you for the tip @jeffreytse.
