### ISSUE TITLE
No repo name found

### ISSUE THREAD

**Issue by ryan961** [jeffreytse/jekyll-deploy-action#34]
https://github.com/ryan961/ryan961.github.io/runs/5349522506?check_suite_focus=true

**Comment by jeffreytse** [comment]
Hi @ryan961 

I think your issue is that you have [a wrong token]( (https://github.com/ryan961/ryan961.github.io/blob/571a5ee25d53d9e3ed3300182076e646e17961ea/.github/workflows/deploy.yml#L26). GitHub will auto create a token called `GITHUB_TOKEN` for you by default, you just need to use it directly as below snippet.

```yml
token: ${{ secrets.GITHUB_TOKEN }}
```

Thanks & Regards

**Comment by ryan961** [comment]
I have changed it, it still failed.
https://github.com/ryan961/ryan961.github.io/runs/5350192317?check_suite_focus=true

**Comment by jeffreytse** [comment]
@ryan961 

It's another issue, as you haven't configured `repository` field in your `_config.yml`. Please add configuration as below

```yml
repository: <username>/<your_repository>
```

Thanks & Regards

**Comment by ryan961** [comment]
> 

Thank you for reply, it's ok!

**Comment by ryan961** [comment]
> Hi @ryan961
> 
> It's another issue, as you haven't configured `repository` field in your `_config.yml`. Please add configuration as below
> 
> ```yaml
> repository: <username>/<your_repository>
> ```
> 
> Thanks & Regards

Thank you for reply, it's ok!

**Comment by ryan961** [comment]
hi,  I have two repos that are identical to each other. I am attempting to automate pushing to the public repo from the private one using this action, but I am having issues pushing. 
```
...
remote: Permission to ryan961/ryan961.github.io.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/ryan961/ryan961.github.io.git/': The requested URL returned error: 403
...
```
https://github.com/ryan961/note/runs/5356819165?check_suite_focus=true.
so, I need to create a Personal Access Token (PAT)? or this operation is not supported ? @jeffreytse

**Comment by jeffreytse** [comment]
Hi @ryan961 

You can try to create your [Personal Access Token](https://github.com/jeffreytse/jekyll-deploy-action) according the README and set your repository as below:

```yml
token: ${{ secrets.MY_PERSONAL_TOKEN }}
repository: 'ryan961.github.io.git'
```

Thanks & Regards

**Comment by Freed-Wu** [comment]
> Please set the TOKEN environment variable.
>
> I think your issue is that you have a wrong token. GitHub will auto create a token called GITHUB_TOKEN for you by default, you just need to use it directly as below snippet.
>
> token: `${{ secrets.GITHUB_TOKEN }}`

Why not let `${{ secrets.GITHUB_TOKEN }}` to be the default value of `token`? and let `github` as the default value of `provider`?

**Comment by jeffreytse** [comment]
@Freed-Wu Actually, the value `github` is the default value of `provider`.
