### ISSUE TITLE
Add an option to only build without publishing

### ISSUE THREAD

**Issue by peimanja** [jeffreytse/jekyll-deploy-action#36]
We still would like to check if build passes on pull requests without publishing the site.

**Comment by jeffreytse** [comment]
Hi @peimanja 

Thanks for the suggestion, I will take a consideration and work on this as soon as possible. And welcome to star this project for further update in the future.

Thanks & Regards

**Comment by jeffreytse** [comment]
Hi @peimanja 

I have a question on the requirement, why you don't want to create a branch for test purpose?

Thanks & Regards

**Comment by peimanja** [comment]
> Hi @peimanja
> 
> I have a question on the requirement, why you don't want to create a branch for test purpose?
> 
> Thanks & Regards

Thanks for he quick response. On pull requests we deploy a preview version  on netlify using https://github.com/nwtgck/actions-netlify action and after merging the PR we deploy it on Github pages

right now we use https://github.com/helaili/jekyll-action action but we are looking for a better maintained action and yours looks very good.

so adding an option like this:
```
build_only: ${{ github.event_name == 'pull_request' }}
```
would only build but won't publish it to github pages branch

**Comment by itrich** [comment]
Same here! We're looking for a way to build the site on every branch but only pushing if the source branch is 'main'. This would allow us to test pull requests before merging.

**Comment by jeffreytse** [comment]
@itrich Agree with you, currently I am busy, but I will work on this as soon as possible. : )

**Comment by ZibingZhang** [comment]
Just wanted to add that another use case (the one I'm looking for) would be when I have multiple sub directories that need building before deploying all together, e.g. a `jekyll` subdir and a `react-project` subdir. In the meantime I've taken to cloning this repo locally and removing the publishing functionality. Thanks for the amazing action!

**Comment by jeffreytse** [comment]
Hi @peimanja @itrich,

Thanks for your issue and patience for the feature, now I have added this feature in the latest version. Welcome to update for  better convenience.

Thanks & Regards
