### ISSUE TITLE
add an optional choice to build using the source file

### ISSUE THREAD

**Issue by wholon** [jeffreytse/jekyll-deploy-action#39]
I already use this action and it's pretty good to solve my problem for using other plugins.

but I found I can't build my site using my local theme, which means I need to specific a remote-theme and I can't configure it locally.

Is there any possible to build my site and using my own theme?

My English is not very well, hope you can understand what I mean. ^-^

**Comment by wholon** [comment]
> I already use this action and it's pretty good to solve my problem for using other plugins.
> 
> but I found I can't build my site using my local theme, which means I need to specific a remote-theme and I can't configure it locally.
> 
> Is there any possible to build my site and using my own theme?
> 
> My English is not very well, hope you can understand what I mean. ^-^

I don't know what I have done, but this issue has already solved.

Thx for the awesome action.

**Comment by wholon** [comment]
> > I already use this action and it's pretty good to solve my problem for using other plugins.
> > but I found I can't build my site using my local theme, which means I need to specific a remote-theme and I can't configure it locally.
> > Is there any possible to build my site and using my own theme?
> > My English is not very well, hope you can understand what I mean. ^-^
> 
> I don't know what I have done, but this issue has already solved.
> 
> Thx for the awesome action.

It seems like the URLs generated by this method would add /pages/GitHubUsername/ as base_url，that's why all of my theme files had lost.

So I add `base_url: ""` in my `_config` file and everything comes back.

**Comment by jeffreytse** [comment]
Hi @wholon 

Thanks for your issue, is it that you have settled down your issue?

Thanks & Regards
