### ISSUE TITLE
How do I use pre_build_commands?

### ISSUE THREAD

**Issue by oakjelly21** [jeffreytse/jekyll-deploy-action#45]
I want to use the vega-lite diagram library along with a jekyll plugin. 
how do I use the pre build commands to run npm install?
I want to install the diagram library use the command:
npm install -g vega-cli vega-lite

**Comment by jeffreytse** [comment]
Hi @oakjelly21 

This action is based on Arch Linux, so you can run any commands supported by Arch Linux, you can see installation instructions from Node official website, learn how to install `nodejs` and `npm`.

Reference: https://nodejs.org/en/download/package-manager/#arch-linux

```yml
pre_build_commands: 'pacman -S --noconfirm nodejs npm && npm install -g vega-cli vega-lite'
```

Thanks & Regards

**Comment by oakjelly21** [comment]
Thank you for the tip. However, the build fails.
![image](https://user-images.githubusercontent.com/49606481/170413227-53da5f9f-cbb6-49d3-820e-89874cc9ee02.png)
I tried running the command on my PC and it worked. I am not sure if it is a arch linux problem or a something to do with the action.
I searched around the web a lot, but cant seem to find anything that works. A forum suggested that I use -Syu and omit -g, but that does not seem to work either.
I do have to add that npm install does work. I tried chalk it works. So feel free to close the issue if it is not within the scope of this issue
The full log if you need it.
https://github.com/oakjelly21/oakjelly21.github.io/runs/6603657911?check_suite_focus=true
