### ISSUE TITLE
Relative urls broken

### ISSUE THREAD

**Issue by ConorSheehan1** [jeffreytse/jekyll-deploy-action#48]
`relative_url` and `absolute_url` filters are returning weird values for me.

e.g. `{{'assets/js/lightbox_custom.js' | absolute_url }}` returns `https://github.com/pages/ConorSheehan1/assets/js/lightbox_custom.js`.
it seems baseurl is somehow `https://github.com/pages/ConorSheehan1` when it used to be, and should be `https://conorsheehan1.github.io`. I'd expect `https://conorsheehan1.github.io//assets/js/lightbox_custom.js` as the filter output.

I've tried loads of different configs, but my site is completely broken :(
https://github.com/ConorSheehan1/ConorSheehan1.github.io

Any idea how I can fix this?

**Comment by ConorSheehan1** [comment]
I finally got it working. Here's the commit that fixed it : https://github.com/ConorSheehan1/ConorSheehan1.github.io/commit/f4558c530e54752623eeae9ef22de803e8f53466

[Despite some contradictory advice](https://stackoverflow.com/questions/48197580/jekyll-theme-does-not-work-on-github-pages-but-works-locally/64778847#64778847) *adding* `baseurl: ""` to _config.yml and using the defaults for this action fixed my build.

**Comment by jeffreytse** [comment]
Hi @ConorSheehan1 

It's great to hear that you have fixed this issue. Hope you have a good weekend! : )

Thanks & Regards
