### ISSUE TITLE
Error when trying to run libvips for Jekyll-Picture-Tag

### ISSUE THREAD

**Issue by shinwookim** [jeffreytse/jekyll-deploy-action#49]
```
/github/workspace/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.5/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'vips.so.42': vips.so.42: cannot open shared object file: No such file or directory. (LoadError)
Could not open library 'libvips.so.42': libvips.so.42: cannot open shared object file: No such file or directory
```

[1_build_and_deploy.txt](https://github.com/jeffreytse/jekyll-deploy-action/files/9175438/1_build_and_deploy.txt)

**Comment by shinwookim** [comment]
[1_build_and_deploy.txt](https://github.com/jeffreytse/jekyll-deploy-action/files/9175438/1_build_and_deploy.txt)

**Comment by shinwookim** [comment]
Solved by installing LibVips via Pre-build commands

**Comment by Benau** [comment]
seems that the repo owner need to reinstall jeykll picture tag and rebuild it against latest libvips.so

**Comment by jeffreytse** [comment]
Hi @shinwookim 

Have you settled down this issue?

Thanks & Regards

**Comment by kKerem** [comment]
Same issue. Works on local but failing on github actions. I did what was said but it didn't work.

**Comment by jeffreytse** [comment]
Hi @kKerem , could you share me your action YAML file? so that I can help you check what happened.

**Comment by kKerem** [comment]
> Hi @kKerem , could you share me your action YAML file? so that I can help you check what happened.

https://github.com/kKerem/kkerem.github.io/blob/main/.github/workflows/jekyll.yml

https://github.com/kKerem/kkerem.github.io/actions/runs/3855864257/jobs/6571392481

**Comment by jackbondpreston** [comment]
Are you actually using jekyll-deploy-action? can't see it in this .yml

**Comment by jeffreytse** [comment]
> Are you actually using jekyll-deploy-action? can't see it in this .yml

Agree with you.

**Comment by kKerem** [comment]
I put the wrong yaml file my bad im quite new on this things. Its working now but im struggling with cache issue. My jekyll page still showing the first commit. Do I need to do something else? I couldn't figure it out.

updated yaml https://github.com/kKerem/kkerem.github.io/blob/main/.github/workflows/jekyll.yml

https://github.com/kKerem/kkerem.github.io/blob/gh-pages/index.html#L236
https://kkerem.github.io/
