### ISSUE TITLE
Is it "TOKEN" or "GH_TOKEN"?

### ISSUE THREAD

**Issue by iveney** [jeffreytse/jekyll-deploy-action#6]
The [code](https://github.com/jeffreytse/jekyll-deploy-action/blob/0bb9ed9e4d5afd759c836ee9a4c7de73629673cc/action.yml#L8) and my failed workflow seems suggesting me to use "TOKEN", while the doc says "GH_TOKEN".

I think it should be "TOKEN" per the code?

**Comment by jeffreytse** [comment]
Hi @iveney 

Thank you for your using this action. And for the "TOKEN", you should follow below:

About how we to provide permissions for this action to push to the `gh-pages` branch:

- Create a [Personal Token](https://github.com/settings/tokens) with **repos permissions** and copy the value.
- Go to your repository’s Settings and then switch to the Secrets tab.
- Create a token named `GH_TOKEN` **(important)** using the value copied.

Thanks and regards

**Comment by iveney** [comment]
Thanks! Somehow it didn't work at the first try. `GH_TOKEN` does work for me now.
