### ISSUE TITLE
Error as bundler requires Ruby version >=3.0.0

### ISSUE THREAD

**Issue by jeffreytse** [jeffreytse/jekyll-deploy-action#70]
The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.4.22. Try installing it with `gem install bundler -v 2.4.22`
	bundler requires Ruby version >= 3.0.0. The current ruby version is 2.7.8.225.

**Comment by jeanjerome** [comment]
Works like a charm... if you don't forget to set `bundler_ver: ''` as parameter of this new action ;)
Thanks.
