### ISSUE TITLE
Archlinux keyring not updating

### ISSUE THREAD

**Issue by EngiTom** [jeffreytse/jekyll-deploy-action#73]
When I attempted to update my Jekyll-based blog today (an older fork of the Minimal Mistakes theme), the deploy failed with the following error
[0_build_and_deploy.txt](https://github.com/jeffreytse/jekyll-deploy-action/files/13803814/0_build_and_deploy.txt)

Looking up the error at the bottom of the file, it seems like the cause is that keyring is not updated. Is this an issue with the deploy action? Or should I fork the newest version of the theme?

**Comment by ambersun1234** [comment]
same here with the following error
```
error: ruby-uri: signature from "Levente Polyak (anthraxx) <levente@leventepolyak.net>" is unknown trust
:: File /var/cache/pacman/pkg/ruby-uri-0.12.1-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
error: failed to commit transaction (invalid or corrupted package)
```

**Comment by pgpbpadilla** [comment]
+1

**Comment by pgpbpadilla** [comment]
This seems to fix it but it makes the build take longer:

```bash
pacman-key --refresh-keys 
```

**Comment by pgpbpadilla** [comment]
Added also #75 

doing `--refresh-keys` at runtime results in a build time increase from ~56 seconds to ~8 minutes 😨 

I'm hopping that by caching that in the resulting Docker image will make builds that benefit from it to go back to under a minute 🤞

**Comment by jeffreytse** [comment]
I'm focusing on settling this issue, please be patient. : )

**Comment by jeffreytse** [comment]
Hi @EngiTom @ambersun1234 @pgpbpadilla 

This issue has been fixed, as the docker image [archlinux:base-devel](https://hub.docker.com/layers/library/archlinux/base-devel/images/sha256-cb08e2ce287c30f5484e0264132e697fb36f01734c9489492ff5c3f3db729812?context=explore) has been updated one day ago.

![docker-img](https://github.com/jeffreytse/jekyll-deploy-action/assets/9413601/2ff73bc6-fe47-41d3-b852-6149cfc26365)

Please try to build your jekyll site again. : )

Thanks & Regards

**Comment by pgpbpadilla** [comment]
Super! I will check it out. I have a question though. I started thinking if it would be a simpler setup to base the Docker image on the official Ruby image. Have you ever thought about doing that?

**Comment by jeffreytse** [comment]
Hi @pgpbpadilla,

At the very beginning, it actually used the official Ruby image. I'm planning to make a custom image, welcome to star this project for further update in the future.

Thanks & Regards

**Comment by pgpbpadilla** [comment]
Confirmed. Everything works now ❤️

**Comment by pgpbpadilla** [comment]
So there was no actual change in the Github action, right? I could not find (I didn't look very hard though) the commit in the arch-linux that says something about the keyring needing an update 🤔

**Comment by jeffreytse** [comment]
> So there was no actual change in the Github action, right? I could not find (I didn't look very hard though) the commit in the arch-linux that says something about the keyring needing an update 🤔

You can see this layer will copy the whole file system which is the latest version.
 
![image](https://github.com/jeffreytse/jekyll-deploy-action/assets/9413601/5ac2d951-5f4f-4db6-9dac-30c8fde50d0b)
